exclude: ^tests/|^temp_upload\.py

repos:
  - repo: local
    hooks:
      - id: docstring-validator
        name: PEP 257 Docstring Check
        entry: pydocstyle
        language: python
        types: [python]
        args: ["--convention=numpy"]