site_name: DocuGenius Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight

# FIX: Make sure 'plugins' is not indented inside 'theme'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

nav:
  - Project Description: index.md
  - Usage Guide: usage.md
  - Configuration Guide: configuration.md
  - Contributing: contributing.md
  - Quick Start Example: example.md
  - Technical Details:
      - History: changelog.md
      - Troubleshooting & FAQ: faq.md
      - Benchmarks: benchmarks.md
      - API Reference: api_ref.md
      - License: license.md

extra_css:
  - stylesheets/extra.css